export const ApiEndpoint = {
  login: "staff_student_login/staff_login",
  master_soft_delete: "comman_function/soft_delete",
  common_api: {
    deportment_list: "comman_function/get_dept_programtype",
    batch_cycle_list: "comman_function/batch_cycle_list",
    get_semester_list: "comman_function/get_semester_list",
    occubationoption: "course_type/get_temp_cia_occasion",
    get_batch_terms: "class_time_table/get_batch_terms",
    gettimetablesession: "class_time_table/fetch_student_section_list_options_progress",
    get_section_list: 'comman_function/fetch_student_section_list',
    get_cycle_semester_list: 'comman_function/get_cycle_semester_list',
    fetch_student_section_list:'comman_function/fetch_student_section_list',
    fetch_student_course:"course_reg/fetch_student_course_usn",
  },
  allMaster: {
    get_all_masters_list: "all_master/all_masters_list",
    get_all_org_info: "",
    parents_occupation_master_list: "all_master/parents_occupation_master_list",
    save_parents_occupation_master: "all_master/save_parents_occupation_master",
    event_type_master_list: "all_master/event_type_master_list",
    save_event_type_master: "all_master/save_event_type_master",
    course_type_list: "all_master/course_type_list",
    save_course_type: "all_master/save_course_type",
    occasion_type_list: "all_master/occasion_type_list",
    save_occasion_type: "all_master/save_occasion_type",
    exam_session_list: "all_master/exam_session_list",
    save_exam_session: "all_master/save_exam_session",
    caste_list: "all_master/caste_list",
    save_caste: "all_master/save_caste",
    city_list: "all_master/city_list",
    exam_hall_list: "all_master/exam_hall_list",
    save_hall: "all_master/save_hall",
    state_list: "comman_function/state_list",
    country_list:'/comman_function/country_list',
    common_city_list: 'comman_function/city_list'
  },
  department: {
    save_department: "department/save_department",
    department_list: "comman_function/department_list",
  },
  program: {
    save_program_type: "program_type/save_program_type",
    program_type_list: "comman_function/program_type_list",
    save_program: "program/save_program",
    program_list: "comman_function/get_programs",
  },
  courseAllocation: {
    fetch_course: 'user_courses/fetch_course',
    get_user_allocated_courses:'user_courses/get_user_allocated_courses'
  },
  user_master: {
    user_master_save: "user_master/save_user",
    user_master_list: "user_master/get_user_master_list",
    user_master_list_details: "user_master/get_user_master_list_details",
    reset_password: "/user_master/reset_password",
  },
  user_access: {
    user_menu_permissions: "user_acccess/user_menu_permissions",
    get_users_with_permissions: "user_acccess/get_users_with_permissions",
    save_user_permissions: "user_acccess/save_user_permissions",
  },
  user_role: {
    get_user_Menus_roles: "user_roles/user_menu_roles",
    get_user_roles: "user_roles/get_user_roles",
    save_user_roles: "user_roles/save_user_roles",
    delete_role: "user_roles/delete_role",
  },
  academicCalendar: {
    getTabledata: "academic_calender/get_exam_event",
    saveAcadamicEvent: "academic_calender/save_event",
    is_result_year: "academic_calender/is_result_year",
  },
  academicBatch: {
    grade_type_details: "academic_batch/grade_type_details",
    getTabledata: "comman_function/academic_batch_list",
    saveAcadamicBatch: "academic_batch/save_academic_batch",
  },
  semester: {
    isSemester: "semester/is_semester",
    getTabledata: "comman_function/semester_list",
    save: "semester/save_semester",
    update: "semester/check_std_register_and_update_semester",
    fetch_semesterlist: "semester/fetch_semesterlist",
  },
  eventCalender: {
    getTableList: "event_calender/event_calendar_list",
    save: "event_calender/save_event_calendar_details",
  },
  course: {
    courseGroupList: "course_type_list",
    courseList: "course_type/get_course_list",
    courseSave: "course_type/save_course",
    batchlist: "course_type/lab_batch_list",
    saveBatch: "course_type/save_lab_batch",
    occasionlist: "course_type/fetch_occasion",
    saveoccasionlist: "course_type/save_occasionlist",
    deleteOccasion: "course_type/remove_occasion",
    saveoccasion: "course_type/save_occasion",
    deleteCourse: "course_type/delete_course",
    bulkImport: "course_type/import",
  },
  classTimeTable: {
    tableList: "class_time_table/get_first_year_time_table_data",
    saveClassTimeTable: "",
  },
  studentRegistation: {
    get_student_reg_list: "registration_std_lite/get_student_reg_list",
    save: "registration_std_lite/save_student_reg",
    resetPassword: "registration_std_lite/student_reset_password",
    bulkImport: "",
    upload_image: "registration_std_lite/upload_image",
    get_student_admission_reg_list: "registration_std/get_student_admission_list_detail",
    save_admission_details: "registration_std/save_admission_details",
    save_parent_information: "registration_std/save_parent_information",
    save_education_details: "registration_std/save_education_details",
    get_student_education_detail :'registration_std/get_student_education_detail',
    save_address_details:'registration_std/save_address_details',
    get_student_address_detail: 'registration_std/get_student_address_detail',
    get_student_certificate_detail:'registration_std/get_student_certificate_detail',
    CertificateFormSave: 'registration_std/save_student_certificate_detail'
  },
  studentAllocation : {
    fetch_course_option:'student_alc/fetch_course',
    lab_batch_list_option:'student_alc/lab_batch_list',
    fetch_student_info: 'student_alc/fetch_student_info',
    save_fetch_student_info: 'student_alc/to_student_info',
    fetch_students_section: 'student_alc/fetch_students_section',
    save_fetch_students_section:'student_alc/save_section_students',
    get_cycle_student_list: 'student_alc/get_cycle_students',
    save_cyclewise_student_allocation : 'student_alc/save_cycle_students',
    get_students_count_for_cycle:'student_alc/get_students_count_for_cycle',
    get_section_wise_cycle_list: 'student_alc/get_cycle_wise_students',
    save_cycle_student_allocation: 'student_alc/save_cycle_wise_students',
    fetch_lab_batch_student_info: 'student_alc/fetch_lab_batch_student_info'
  },
  courseRegistation: {
    get_credits: 'course_reg/get_credits_by_usn',
    get_credits_bulk:'registration_std_lite/get_credits_bulk',
    course_registration_list:"course_reg/fetch_student_course_registration_list"
  },
  bulkCourseRegister: {
    get_both_course_List_manatry_student: 'bulk_reg/get_student_bulk_reg_list',
    get_elective_student_list: '',
    elective_student_registration: '',
    bulk_student_registration: '',
  },
  StudentExamRegister: {
    studentExamRegister_list: 'fetch_course_registration_list',
    save_studentExamRegister: 'to_register_update',
  },
  examEvent: {
    examEventlist: "comman_function/fetch_result_year",
  },
  examEligiblity: {
    eligiblity_fetch_student_course: "staff/fetch_student_course",
    get_open_elective_students: "staff/get_open_elective_students",
    get_open_elective_att_students: "staff/get_open_elective_att_students",
  },
  cia: {
    get_cia_entry_list: ''
  },
  examnation: {
    examFirstYearTimeTableList: "examination/get_time_table_list",
    examFirstYearTimeTableFormList: "",
    batchwiseExamTimeTableList: "",
    BatchwiseexamTimeTableFormList: "examination/get_course_list_labtheory",
    get_labbatch_allocation_list: "examination/get_labbatch_allocation_list",
    get_lab_batch_students: "examination/get_lab_batch_students",
    result_withheald: "",
    courses_list_by_usn: "examination/result_withheald/courses_list_by_usn",
  },
  evalution: {
    examattendancelist: "",
    exammarksStudentlist: "staff/fetch_student_course",
    GradeProcessingList: "",
    gradeProcessingAction: "",
    reEvaluateMarkEntryList: "",
    verticalarMobility: "",
  },
} as const;
